const types = {
    MOVE: 'MOVE'
  , TAKE_PIECE: 'TAKE_PIECE'
  , PLAY_LOCAL: 'PLAY_LOCAL'
  , PLAY_ONLINE: 'PLAY_ONLINE'
  , SELECT_GAME: 'SELECT_GAME'
  , LOGIN: 'LOGIN'
  , LOGOUT: 'LOGOUT'
  , PRE_GAME: 'PRE_GAME'
  , DESELECT_GAME: 'DESELECT_GAME'
  , UPDATE_TITLE: 'UPDATE_TITLE'
  , UPDATE_META: 'UPDATE_META'
  , CHAT_MESSAGE: 'CHAT_MESSAGE'

  , ADD_PUBLIC_GAMES: 'ADD_PUBLIC_GAMES'
  , ADD_ACTIVE_GAMES: 'ADD_ACTIVE_GAMES'
  , ADD_PUBLIC_REQ: 'ADD_PUBLIC_REQ'
  , ADD_OUTBOUND_REQ: 'ADD_OUTBOUND_REQ'
  , ADD_INBOUND_REQ: 'ADD_INBOUND_REQ'
  , EDIT_REQ: 'EDIT_REQ'
}

export default types
