const types = {
    MOVE: 'MOVE'
  , TAKE_PIECE: 'TAKE_PIECE'
  , PLAY_LOCAL: 'PLAY_LOCAL'
  , PLAY_ONLINE: 'PLAY_ONLINE'
  , SELECT_GAME: 'SELECT_GAME'
  , LOGIN: 'LOGIN'
  , LOGOUT: 'LOGOUT'
  , PRE_GAME: 'PRE_GAME'
  , DESELECT_GAME: 'DESELECT_GAME'
  , UPDATE_TITLE: 'UPDATE_TITLE'
  , UPDATE_META: 'UPDATE_META'
  , CHAT_MESSAGE: 'CHAT_MESSAGE'

  , ADD_PUBLIC_GAME: 'ADD_PUBLIC_GAME'
  , REFRESH_PUBLIC_GAMES: 'REFRESH_PUBLIC_GAMES'

  , ADD_ACTIVE_GAME: 'ADD_ACTIVE_GAME'
  , REFRESH_ACTIVE_GAMES: 'REFRESH_ACTIVE_GAMES'

  , ADD_PUBLIC_REQ: 'ADD_PUBLIC_REQ'
  , REFRESH_PUBLIC_REQS: 'REFRESH_PUBLIC_REQS'

  , ADD_OUTBOUND_REQ: 'ADD_OUTBOUND_REQ'
  , REFRESH_OUTBOUND_REQS: 'REFRESH_OUTBOUND_REQS'

  , ADD_INBOUND_REQ: 'ADD_INBOUND_REQ'
  , REFRESH_INBOUND_REQS: 'REFRESH_INBOUND_REQS'

  , EDIT_REQ: 'EDIT_REQ'
  , DELETE_REQ: 'DELETE_REQ'

  , REFRESH_NOTIFICATIONS: 'REFRESH_NOTIFICATIONS'
  , ADD_NOTIFICATION: 'ADD_NOTIFICATION'
}

export default types
